//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Feedback
{
    public partial class Comment
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Text
        {
            get;
            set;
        }
    
        public virtual string AuthorName
        {
            get;
            set;
        }
    
        public virtual string AuthorId
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual System.Guid ReportId
        {
            get { return _reportId; }
            set
            {
                if (_reportId != value)
                {
                    if (Report != null && Report.Id != value)
                    {
                        Report = null;
                    }
                    _reportId = value;
                }
            }
        }
        private System.Guid _reportId;

        #endregion
        #region Navigation Properties
    
        public virtual Report Report
        {
            get { return _report; }
            set
            {
                if (!ReferenceEquals(_report, value))
                {
                    var previousValue = _report;
                    _report = value;
                    FixupReport(previousValue);
                }
            }
        }
        private Report _report;

        #endregion
        #region Association Fixup
    
        private void FixupReport(Report previousValue)
        {
            if (previousValue != null && previousValue.Comments.Contains(this))
            {
                previousValue.Comments.Remove(this);
            }
    
            if (Report != null)
            {
                if (!Report.Comments.Contains(this))
                {
                    Report.Comments.Add(this);
                }
                if (ReportId != Report.Id)
                {
                    ReportId = Report.Id;
                }
            }
        }

        #endregion
    }
}
