//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.EntityClient;
using System.Data.Objects;

namespace Feedback
{
    public partial class FeedbackModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=FeedbackModelContainer";
        public const string ContainerName = "FeedbackModelContainer";
    
        #region Constructors
    
        public FeedbackModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public FeedbackModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public FeedbackModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Report> Reports
        {
            get { return _reports  ?? (_reports = CreateObjectSet<Report>("Reports")); }
        }
        private ObjectSet<Report> _reports;
    
        public ObjectSet<Comment> Comments
        {
            get { return _comments  ?? (_comments = CreateObjectSet<Comment>("Comments")); }
        }
        private ObjectSet<Comment> _comments;

        #endregion
    }
}
