//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Administrator : BaseUser
    {
        #region Primitive Properties
    
        public virtual string Login
        {
            get;
            set;
        }
    
        public virtual System.Guid Password
        {
            get;
            set;
        }
    
        public virtual System.Guid Salt
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<BlockedRecord> BlockedRecords
        {
            get
            {
                if (_blockedRecords == null)
                {
                    var newCollection = new FixupCollection<BlockedRecord>();
                    newCollection.CollectionChanged += FixupBlockedRecords;
                    _blockedRecords = newCollection;
                }
                return _blockedRecords;
            }
            set
            {
                if (!ReferenceEquals(_blockedRecords, value))
                {
                    var previousValue = _blockedRecords as FixupCollection<BlockedRecord>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBlockedRecords;
                    }
                    _blockedRecords = value;
                    var newValue = value as FixupCollection<BlockedRecord>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBlockedRecords;
                    }
                }
            }
        }
        private ICollection<BlockedRecord> _blockedRecords;

        #endregion

        #region Association Fixup
    
        private void FixupBlockedRecords(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BlockedRecord item in e.NewItems)
                {
                    item.Administrator = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BlockedRecord item in e.OldItems)
                {
                    if (ReferenceEquals(item.Administrator, this))
                    {
                        item.Administrator = null;
                    }
                }
            }
        }

        #endregion

    }
}
