//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Bulletin
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual System.Guid OwnerId
        {
            get { return _ownerId; }
            set
            {
                if (_ownerId != value)
                {
                    if (Owner != null && Owner.Id != value)
                    {
                        Owner = null;
                    }
                    _ownerId = value;
                }
            }
        }
        private System.Guid _ownerId;

        #endregion

        #region Navigation Properties
    
        public virtual GroupMember Owner
        {
            get { return _owner; }
            set
            {
                if (!ReferenceEquals(_owner, value))
                {
                    var previousValue = _owner;
                    _owner = value;
                    FixupOwner(previousValue);
                }
            }
        }
        private GroupMember _owner;

        #endregion

        #region Association Fixup
    
        private void FixupOwner(GroupMember previousValue)
        {
            if (previousValue != null && previousValue.Bulletins.Contains(this))
            {
                previousValue.Bulletins.Remove(this);
            }
    
            if (Owner != null)
            {
                if (!Owner.Bulletins.Contains(this))
                {
                    Owner.Bulletins.Add(this);
                }
                if (OwnerId != Owner.Id)
                {
                    OwnerId = Owner.Id;
                }
            }
        }

        #endregion

    }
}
