//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Federation.Core
{
    public partial class EntityModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=EntityModelContainer";
        public const string ContainerName = "EntityModelContainer";
    
        #region Constructors
    
        public EntityModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EntityModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EntityModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<BaseUser> BaseUserSet
        {
            get { return _baseUserSet  ?? (_baseUserSet = CreateObjectSet<BaseUser>("BaseUserSet")); }
        }
        private ObjectSet<BaseUser> _baseUserSet;
    
        public ObjectSet<Group> GroupSet
        {
            get { return _groupSet  ?? (_groupSet = CreateObjectSet<Group>("GroupSet")); }
        }
        private ObjectSet<Group> _groupSet;
    
        public ObjectSet<GroupMember> GroupMemberSet
        {
            get { return _groupMemberSet  ?? (_groupMemberSet = CreateObjectSet<GroupMember>("GroupMemberSet")); }
        }
        private ObjectSet<GroupMember> _groupMemberSet;
    
        public ObjectSet<Tag> TagSet
        {
            get { return _tagSet  ?? (_tagSet = CreateObjectSet<Tag>("TagSet")); }
        }
        private ObjectSet<Tag> _tagSet;
    
        public ObjectSet<Expert> ExpertSet
        {
            get { return _expertSet  ?? (_expertSet = CreateObjectSet<Expert>("ExpertSet")); }
        }
        private ObjectSet<Expert> _expertSet;
    
        public ObjectSet<ExpertVote> ExpertVoteSet
        {
            get { return _expertVoteSet  ?? (_expertVoteSet = CreateObjectSet<ExpertVote>("ExpertVoteSet")); }
        }
        private ObjectSet<ExpertVote> _expertVoteSet;
    
        public ObjectSet<Candidate> CandidateSet
        {
            get { return _candidateSet  ?? (_candidateSet = CreateObjectSet<Candidate>("CandidateSet")); }
        }
        private ObjectSet<Candidate> _candidateSet;
    
        public ObjectSet<Address> AddressSet
        {
            get { return _addressSet  ?? (_addressSet = CreateObjectSet<Address>("AddressSet")); }
        }
        private ObjectSet<Address> _addressSet;
    
        public ObjectSet<City> CitySet
        {
            get { return _citySet  ?? (_citySet = CreateObjectSet<City>("CitySet")); }
        }
        private ObjectSet<City> _citySet;
    
        public ObjectSet<Comment> CommentSet
        {
            get { return _commentSet  ?? (_commentSet = CreateObjectSet<Comment>("CommentSet")); }
        }
        private ObjectSet<Comment> _commentSet;
    
        public ObjectSet<Message> MessageSet
        {
            get { return _messageSet  ?? (_messageSet = CreateObjectSet<Message>("MessageSet")); }
        }
        private ObjectSet<Message> _messageSet;
    
        public ObjectSet<Content> ContentSet
        {
            get { return _contentSet  ?? (_contentSet = CreateObjectSet<Content>("ContentSet")); }
        }
        private ObjectSet<Content> _contentSet;
    
        public ObjectSet<Bulletin> BulletinSet
        {
            get { return _bulletinSet  ?? (_bulletinSet = CreateObjectSet<Bulletin>("BulletinSet")); }
        }
        private ObjectSet<Bulletin> _bulletinSet;
    
        public ObjectSet<Region> RegionSet
        {
            get { return _regionSet  ?? (_regionSet = CreateObjectSet<Region>("RegionSet")); }
        }
        private ObjectSet<Region> _regionSet;
    
        public ObjectSet<BlockedRecord> BlockedRecordSet
        {
            get { return _blockedRecordSet  ?? (_blockedRecordSet = CreateObjectSet<BlockedRecord>("BlockedRecordSet")); }
        }
        private ObjectSet<BlockedRecord> _blockedRecordSet;
    
        public ObjectSet<Invite> InviteSet
        {
            get { return _inviteSet  ?? (_inviteSet = CreateObjectSet<Invite>("InviteSet")); }
        }
        private ObjectSet<Invite> _inviteSet;
    
        public ObjectSet<Coauthor> CoauthorSet
        {
            get { return _coauthorSet  ?? (_coauthorSet = CreateObjectSet<Coauthor>("CoauthorSet")); }
        }
        private ObjectSet<Coauthor> _coauthorSet;
    
        public ObjectSet<Like> LikeSet
        {
            get { return _likeSet  ?? (_likeSet = CreateObjectSet<Like>("LikeSet")); }
        }
        private ObjectSet<Like> _likeSet;
    
        public ObjectSet<MailRecord> MailRecordSet
        {
            get { return _mailRecordSet  ?? (_mailRecordSet = CreateObjectSet<MailRecord>("MailRecordSet")); }
        }
        private ObjectSet<MailRecord> _mailRecordSet;
    
        public ObjectSet<Badge> BadgeSet
        {
            get { return _badgeSet  ?? (_badgeSet = CreateObjectSet<Badge>("BadgeSet")); }
        }
        private ObjectSet<Badge> _badgeSet;
    
        public ObjectSet<ErrorText> ErrorTextSet
        {
            get { return _errorTextSet  ?? (_errorTextSet = CreateObjectSet<ErrorText>("ErrorTextSet")); }
        }
        private ObjectSet<ErrorText> _errorTextSet;
    
        public ObjectSet<Attach> AttachSet
        {
            get { return _attachSet  ?? (_attachSet = CreateObjectSet<Attach>("AttachSet")); }
        }
        private ObjectSet<Attach> _attachSet;
    
        public ObjectSet<ScheduleJob> ScheduleJobSet
        {
            get { return _scheduleJobSet  ?? (_scheduleJobSet = CreateObjectSet<ScheduleJob>("ScheduleJobSet")); }
        }
        private ObjectSet<ScheduleJob> _scheduleJobSet;
    
        public ObjectSet<Album> AlbumSet
        {
            get { return _albumSet  ?? (_albumSet = CreateObjectSet<Album>("AlbumSet")); }
        }
        private ObjectSet<Album> _albumSet;
    
        public ObjectSet<AlbumItem> AlbumItemSet
        {
            get { return _albumItemSet  ?? (_albumItemSet = CreateObjectSet<AlbumItem>("AlbumItemSet")); }
        }
        private ObjectSet<AlbumItem> _albumItemSet;
    
        public ObjectSet<ProfileChangeRequest> ProfileChangeRequestSet
        {
            get { return _profileChangeRequestSet  ?? (_profileChangeRequestSet = CreateObjectSet<ProfileChangeRequest>("ProfileChangeRequestSet")); }
        }
        private ObjectSet<ProfileChangeRequest> _profileChangeRequestSet;
    
        public ObjectSet<SocialAccount> SocialAccountSet
        {
            get { return _socialAccountSet  ?? (_socialAccountSet = CreateObjectSet<SocialAccount>("SocialAccountSet")); }
        }
        private ObjectSet<SocialAccount> _socialAccountSet;
    
        public ObjectSet<ScheduleExecutionInfo> ScheduleExecutionInfoSet
        {
            get { return _scheduleExecutionInfoSet  ?? (_scheduleExecutionInfoSet = CreateObjectSet<ScheduleExecutionInfo>("ScheduleExecutionInfoSet")); }
        }
        private ObjectSet<ScheduleExecutionInfo> _scheduleExecutionInfoSet;
    
        public ObjectSet<Option> OptionSet
        {
            get { return _optionSet  ?? (_optionSet = CreateObjectSet<Option>("OptionSet")); }
        }
        private ObjectSet<Option> _optionSet;
    
        public ObjectSet<SurveyBulletin> SurveyBulletinSet
        {
            get { return _surveyBulletinSet  ?? (_surveyBulletinSet = CreateObjectSet<SurveyBulletin>("SurveyBulletinSet")); }
        }
        private ObjectSet<SurveyBulletin> _surveyBulletinSet;
    
        public ObjectSet<SmsInfo> SmsInfoSet
        {
            get { return _smsInfoSet  ?? (_smsInfoSet = CreateObjectSet<SmsInfo>("SmsInfoSet")); }
        }
        private ObjectSet<SmsInfo> _smsInfoSet;
    
        public ObjectSet<GroupAd> GroupAdSet
        {
            get { return _groupAdSet  ?? (_groupAdSet = CreateObjectSet<GroupAd>("GroupAdSet")); }
        }
        private ObjectSet<GroupAd> _groupAdSet;
    
        public ObjectSet<GroupCategory> GroupCategorySet
        {
            get { return _groupCategorySet  ?? (_groupCategorySet = CreateObjectSet<GroupCategory>("GroupCategorySet")); }
        }
        private ObjectSet<GroupCategory> _groupCategorySet;
    
        public ObjectSet<GroupRating> GroupRatingSet
        {
            get { return _groupRatingSet  ?? (_groupRatingSet = CreateObjectSet<GroupRating>("GroupRatingSet")); }
        }
        private ObjectSet<GroupRating> _groupRatingSet;
    
        public ObjectSet<PayPalVerification> PayPalVerificationSet
        {
            get { return _payPalVerificationSet  ?? (_payPalVerificationSet = CreateObjectSet<PayPalVerification>("PayPalVerificationSet")); }
        }
        private ObjectSet<PayPalVerification> _payPalVerificationSet;
    
        public ObjectSet<UserAuthentificationLog> UserAuthentificationLogSet
        {
            get { return _userAuthentificationLogSet  ?? (_userAuthentificationLogSet = CreateObjectSet<UserAuthentificationLog>("UserAuthentificationLogSet")); }
        }
        private ObjectSet<UserAuthentificationLog> _userAuthentificationLogSet;
    
        public ObjectSet<UserAuthorizationLog> UserAuthorizationLogSet
        {
            get { return _userAuthorizationLogSet  ?? (_userAuthorizationLogSet = CreateObjectSet<UserAuthorizationLog>("UserAuthorizationLogSet")); }
        }
        private ObjectSet<UserAuthorizationLog> _userAuthorizationLogSet;
    
        public ObjectSet<UserPollVoteLog> UserPollVoteLogSet
        {
            get { return _userPollVoteLogSet  ?? (_userPollVoteLogSet = CreateObjectSet<UserPollVoteLog>("UserPollVoteLogSet")); }
        }
        private ObjectSet<UserPollVoteLog> _userPollVoteLogSet;
    
        public ObjectSet<UserRegistrationLog> UserRegistrationLogSet
        {
            get { return _userRegistrationLogSet  ?? (_userRegistrationLogSet = CreateObjectSet<UserRegistrationLog>("UserRegistrationLogSet")); }
        }
        private ObjectSet<UserRegistrationLog> _userRegistrationLogSet;
    
        public ObjectSet<SubscriptionSettings> SubscriptionSettingsSet
        {
            get { return _subscriptionSettingsSet  ?? (_subscriptionSettingsSet = CreateObjectSet<SubscriptionSettings>("SubscriptionSettingsSet")); }
        }
        private ObjectSet<SubscriptionSettings> _subscriptionSettingsSet;

        #endregion

        #region Function Imports
        public ObjectResult<Comment> GetCommentsByFullText(string search_string, Nullable<int> search_count)
        {
    
            ObjectParameter search_stringParameter;
    
            if (search_string != null)
            {
                search_stringParameter = new ObjectParameter("search_string", search_string);
            }
            else
            {
                search_stringParameter = new ObjectParameter("search_string", typeof(string));
            }
    
            ObjectParameter search_countParameter;
    
            if (search_count.HasValue)
            {
                search_countParameter = new ObjectParameter("search_count", search_count);
            }
            else
            {
                search_countParameter = new ObjectParameter("search_count", typeof(int));
            }
            return base.ExecuteFunction<Comment>("GetCommentsByFullText", search_stringParameter, search_countParameter);
        }
        public ObjectResult<Group> GetGroupsByFullText(string search_string, Nullable<int> search_count)
        {
    
            ObjectParameter search_stringParameter;
    
            if (search_string != null)
            {
                search_stringParameter = new ObjectParameter("search_string", search_string);
            }
            else
            {
                search_stringParameter = new ObjectParameter("search_string", typeof(string));
            }
    
            ObjectParameter search_countParameter;
    
            if (search_count.HasValue)
            {
                search_countParameter = new ObjectParameter("search_count", search_count);
            }
            else
            {
                search_countParameter = new ObjectParameter("search_count", typeof(int));
            }
            return base.ExecuteFunction<Group>("GetGroupsByFullText", search_stringParameter, search_countParameter);
        }
        public ObjectResult<Petition> GetPetitionsByFullText(string search_string, Nullable<int> search_count)
        {
    
            ObjectParameter search_stringParameter;
    
            if (search_string != null)
            {
                search_stringParameter = new ObjectParameter("search_string", search_string);
            }
            else
            {
                search_stringParameter = new ObjectParameter("search_string", typeof(string));
            }
    
            ObjectParameter search_countParameter;
    
            if (search_count.HasValue)
            {
                search_countParameter = new ObjectParameter("search_count", search_count);
            }
            else
            {
                search_countParameter = new ObjectParameter("search_count", typeof(int));
            }
            return base.ExecuteFunction<Petition>("GetPetitionsByFullText", search_stringParameter, search_countParameter);
        }
        public ObjectResult<Poll> GetPollsByFullText(string search_string, Nullable<int> search_count)
        {
    
            ObjectParameter search_stringParameter;
    
            if (search_string != null)
            {
                search_stringParameter = new ObjectParameter("search_string", search_string);
            }
            else
            {
                search_stringParameter = new ObjectParameter("search_string", typeof(string));
            }
    
            ObjectParameter search_countParameter;
    
            if (search_count.HasValue)
            {
                search_countParameter = new ObjectParameter("search_count", search_count);
            }
            else
            {
                search_countParameter = new ObjectParameter("search_count", typeof(int));
            }
            return base.ExecuteFunction<Poll>("GetPollsByFullText", search_stringParameter, search_countParameter);
        }
        public ObjectResult<Post> GetPostsByFullText(string search_string, Nullable<int> search_count)
        {
    
            ObjectParameter search_stringParameter;
    
            if (search_string != null)
            {
                search_stringParameter = new ObjectParameter("search_string", search_string);
            }
            else
            {
                search_stringParameter = new ObjectParameter("search_string", typeof(string));
            }
    
            ObjectParameter search_countParameter;
    
            if (search_count.HasValue)
            {
                search_countParameter = new ObjectParameter("search_count", search_count);
            }
            else
            {
                search_countParameter = new ObjectParameter("search_count", typeof(int));
            }
            return base.ExecuteFunction<Post>("GetPostsByFullText", search_stringParameter, search_countParameter);
        }
        public ObjectResult<Survey> GetSurveysByFullText(string search_string, Nullable<int> search_count)
        {
    
            ObjectParameter search_stringParameter;
    
            if (search_string != null)
            {
                search_stringParameter = new ObjectParameter("search_string", search_string);
            }
            else
            {
                search_stringParameter = new ObjectParameter("search_string", typeof(string));
            }
    
            ObjectParameter search_countParameter;
    
            if (search_count.HasValue)
            {
                search_countParameter = new ObjectParameter("search_count", search_count);
            }
            else
            {
                search_countParameter = new ObjectParameter("search_count", typeof(int));
            }
            return base.ExecuteFunction<Survey>("GetSurveysByFullText", search_stringParameter, search_countParameter);
        }
        public ObjectResult<Content> GetOrderedByRatingGroupContent(Nullable<System.Guid> group_id)
        {
    
            ObjectParameter group_idParameter;
    
            if (group_id.HasValue)
            {
                group_idParameter = new ObjectParameter("group_id", group_id);
            }
            else
            {
                group_idParameter = new ObjectParameter("group_id", typeof(System.Guid));
            }
            return base.ExecuteFunction<Content>("GetOrderedByRatingGroupContent", group_idParameter);
        }

        #endregion

    }
}
