//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class ElectionBulletin : Bulletin
    {
        #region Primitive Properties
    
        public virtual System.Guid ElectionId
        {
            get { return _electionId; }
            set
            {
                if (_electionId != value)
                {
                    if (Election != null && Election.Id != value)
                    {
                        Election = null;
                    }
                    _electionId = value;
                }
            }
        }
        private System.Guid _electionId;

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Candidate> Result
        {
            get
            {
                if (_result == null)
                {
                    var newCollection = new FixupCollection<Candidate>();
                    newCollection.CollectionChanged += FixupResult;
                    _result = newCollection;
                }
                return _result;
            }
            set
            {
                if (!ReferenceEquals(_result, value))
                {
                    var previousValue = _result as FixupCollection<Candidate>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupResult;
                    }
                    _result = value;
                    var newValue = value as FixupCollection<Candidate>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupResult;
                    }
                }
            }
        }
        private ICollection<Candidate> _result;
    
        public virtual Election Election
        {
            get { return _election; }
            set
            {
                if (!ReferenceEquals(_election, value))
                {
                    var previousValue = _election;
                    _election = value;
                    FixupElection(previousValue);
                }
            }
        }
        private Election _election;

        #endregion

        #region Association Fixup
    
        private void FixupElection(Election previousValue)
        {
            if (previousValue != null && previousValue.ElectionBulletins.Contains(this))
            {
                previousValue.ElectionBulletins.Remove(this);
            }
    
            if (Election != null)
            {
                if (!Election.ElectionBulletins.Contains(this))
                {
                    Election.ElectionBulletins.Add(this);
                }
                if (ElectionId != Election.Id)
                {
                    ElectionId = Election.Id;
                }
            }
        }
    
        private void FixupResult(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Candidate item in e.NewItems)
                {
                    if (!item.Electorate.Contains(this))
                    {
                        item.Electorate.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Candidate item in e.OldItems)
                {
                    if (item.Electorate.Contains(this))
                    {
                        item.Electorate.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
