//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Expert
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual string Info
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual GroupMember GroupMember
        {
            get { return _groupMember; }
            set
            {
                if (!ReferenceEquals(_groupMember, value))
                {
                    var previousValue = _groupMember;
                    _groupMember = value;
                    FixupGroupMember(previousValue);
                }
            }
        }
        private GroupMember _groupMember;
    
        public virtual ICollection<Tag> Tags
        {
            get
            {
                if (_tags == null)
                {
                    var newCollection = new FixupCollection<Tag>();
                    newCollection.CollectionChanged += FixupTags;
                    _tags = newCollection;
                }
                return _tags;
            }
            set
            {
                if (!ReferenceEquals(_tags, value))
                {
                    var previousValue = _tags as FixupCollection<Tag>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTags;
                    }
                    _tags = value;
                    var newValue = value as FixupCollection<Tag>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTags;
                    }
                }
            }
        }
        private ICollection<Tag> _tags;
    
        public virtual ICollection<ExpertVote> ExpertVotes
        {
            get
            {
                if (_expertVotes == null)
                {
                    var newCollection = new FixupCollection<ExpertVote>();
                    newCollection.CollectionChanged += FixupExpertVotes;
                    _expertVotes = newCollection;
                }
                return _expertVotes;
            }
            set
            {
                if (!ReferenceEquals(_expertVotes, value))
                {
                    var previousValue = _expertVotes as FixupCollection<ExpertVote>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupExpertVotes;
                    }
                    _expertVotes = value;
                    var newValue = value as FixupCollection<ExpertVote>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupExpertVotes;
                    }
                }
            }
        }
        private ICollection<ExpertVote> _expertVotes;

        #endregion

        #region Association Fixup
    
        private void FixupGroupMember(GroupMember previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Expert, this))
            {
                previousValue.Expert = null;
            }
    
            if (GroupMember != null)
            {
                GroupMember.Expert = this;
            }
        }
    
        private void FixupTags(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Tag item in e.NewItems)
                {
                    if (!item.Experts.Contains(this))
                    {
                        item.Experts.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Tag item in e.OldItems)
                {
                    if (item.Experts.Contains(this))
                    {
                        item.Experts.Remove(this);
                    }
                }
            }
        }
    
        private void FixupExpertVotes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ExpertVote item in e.NewItems)
                {
                    item.Expert = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ExpertVote item in e.OldItems)
                {
                    if (ReferenceEquals(item.Expert, this))
                    {
                        item.Expert = null;
                    }
                }
            }
        }

        #endregion

    }
}
