//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class ExpertVote
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual System.Guid ExpertId
        {
            get { return _expertId; }
            set
            {
                if (_expertId != value)
                {
                    if (Expert != null && Expert.Id != value)
                    {
                        Expert = null;
                    }
                    _expertId = value;
                }
            }
        }
        private System.Guid _expertId;
    
        public virtual System.Guid TagId
        {
            get { return _tagId; }
            set
            {
                if (_tagId != value)
                {
                    if (Tag != null && Tag.Id != value)
                    {
                        Tag = null;
                    }
                    _tagId = value;
                }
            }
        }
        private System.Guid _tagId;
    
        public virtual System.Guid GroupMemberId
        {
            get { return _groupMemberId; }
            set
            {
                if (_groupMemberId != value)
                {
                    if (GroupMember != null && GroupMember.Id != value)
                    {
                        GroupMember = null;
                    }
                    _groupMemberId = value;
                }
            }
        }
        private System.Guid _groupMemberId;
    
        public virtual System.DateTime Date
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Expert Expert
        {
            get { return _expert; }
            set
            {
                if (!ReferenceEquals(_expert, value))
                {
                    var previousValue = _expert;
                    _expert = value;
                    FixupExpert(previousValue);
                }
            }
        }
        private Expert _expert;
    
        public virtual Tag Tag
        {
            get { return _tag; }
            set
            {
                if (!ReferenceEquals(_tag, value))
                {
                    var previousValue = _tag;
                    _tag = value;
                    FixupTag(previousValue);
                }
            }
        }
        private Tag _tag;
    
        public virtual GroupMember GroupMember
        {
            get { return _groupMember; }
            set
            {
                if (!ReferenceEquals(_groupMember, value))
                {
                    var previousValue = _groupMember;
                    _groupMember = value;
                    FixupGroupMember(previousValue);
                }
            }
        }
        private GroupMember _groupMember;

        #endregion

        #region Association Fixup
    
        private void FixupExpert(Expert previousValue)
        {
            if (previousValue != null && previousValue.ExpertVotes.Contains(this))
            {
                previousValue.ExpertVotes.Remove(this);
            }
    
            if (Expert != null)
            {
                if (!Expert.ExpertVotes.Contains(this))
                {
                    Expert.ExpertVotes.Add(this);
                }
                if (ExpertId != Expert.Id)
                {
                    ExpertId = Expert.Id;
                }
            }
        }
    
        private void FixupTag(Tag previousValue)
        {
            if (previousValue != null && previousValue.ExpertVotes.Contains(this))
            {
                previousValue.ExpertVotes.Remove(this);
            }
    
            if (Tag != null)
            {
                if (!Tag.ExpertVotes.Contains(this))
                {
                    Tag.ExpertVotes.Add(this);
                }
                if (TagId != Tag.Id)
                {
                    TagId = Tag.Id;
                }
            }
        }
    
        private void FixupGroupMember(GroupMember previousValue)
        {
            if (previousValue != null && previousValue.ExpertVotes.Contains(this))
            {
                previousValue.ExpertVotes.Remove(this);
            }
    
            if (GroupMember != null)
            {
                if (!GroupMember.ExpertVotes.Contains(this))
                {
                    GroupMember.ExpertVotes.Add(this);
                }
                if (GroupMemberId != GroupMember.Id)
                {
                    GroupMemberId = GroupMember.Id;
                }
            }
        }

        #endregion

    }
}
