//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Invite
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Surname
        {
            get;
            set;
        }
    
        public virtual string Patronymic
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string Facebook
        {
            get;
            set;
        }
    
        public virtual string LiveJournal
        {
            get;
            set;
        }
    
        public virtual string Key
        {
            get;
            set;
        }
    
        public virtual byte State
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> BaseUserId
        {
            get { return _baseUserId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_baseUserId != value)
                    {
                        if (Referal != null && Referal.Id != value)
                        {
                            Referal = null;
                        }
                        _baseUserId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<System.Guid> _baseUserId;
    
        public virtual string UserInfo
        {
            get;
            set;
        }
    
        public virtual string Comment
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual BaseUser Referal
        {
            get { return _referal; }
            set
            {
                if (!ReferenceEquals(_referal, value))
                {
                    var previousValue = _referal;
                    _referal = value;
                    FixupReferal(previousValue);
                }
            }
        }
        private BaseUser _referal;
    
        public virtual BaseUser InvitedUser
        {
            get { return _invitedUser; }
            set
            {
                if (!ReferenceEquals(_invitedUser, value))
                {
                    var previousValue = _invitedUser;
                    _invitedUser = value;
                    FixupInvitedUser(previousValue);
                }
            }
        }
        private BaseUser _invitedUser;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupReferal(BaseUser previousValue)
        {
            if (previousValue != null && previousValue.Invites.Contains(this))
            {
                previousValue.Invites.Remove(this);
            }
    
            if (Referal != null)
            {
                if (!Referal.Invites.Contains(this))
                {
                    Referal.Invites.Add(this);
                }
                if (BaseUserId != Referal.Id)
                {
                    BaseUserId = Referal.Id;
                }
            }
            else if (!_settingFK)
            {
                BaseUserId = null;
            }
        }
    
        private void FixupInvitedUser(BaseUser previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.InviteTicket, this))
            {
                previousValue.InviteTicket = null;
            }
    
            if (InvitedUser != null)
            {
                InvitedUser.InviteTicket = this;
            }
        }

        #endregion

    }
}
