//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Poll : Voting
    {
        #region Primitive Properties
    
        public virtual byte Result
        {
            get { return _result; }
            set { _result = value; }
        }
        private byte _result = 0;

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<PollBulletin> Bulletins
        {
            get
            {
                if (_bulletins == null)
                {
                    var newCollection = new FixupCollection<PollBulletin>();
                    newCollection.CollectionChanged += FixupBulletins;
                    _bulletins = newCollection;
                }
                return _bulletins;
            }
            set
            {
                if (!ReferenceEquals(_bulletins, value))
                {
                    var previousValue = _bulletins as FixupCollection<PollBulletin>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBulletins;
                    }
                    _bulletins = value;
                    var newValue = value as FixupCollection<PollBulletin>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBulletins;
                    }
                }
            }
        }
        private ICollection<PollBulletin> _bulletins;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupBulletins(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PollBulletin item in e.NewItems)
                {
                    item.Poll = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PollBulletin item in e.OldItems)
                {
                    if (ReferenceEquals(item.Poll, this))
                    {
                        item.Poll = null;
                    }
                }
            }
        }

        #endregion

    }
}
