//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Post : Content
    {
        #region Primitive Properties
    
        public virtual bool IsExternal
        {
            get;
            set;
        }

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;

        #endregion

    }
}
