//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Region
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<City> Cities
        {
            get
            {
                if (_cities == null)
                {
                    var newCollection = new FixupCollection<City>();
                    newCollection.CollectionChanged += FixupCities;
                    _cities = newCollection;
                }
                return _cities;
            }
            set
            {
                if (!ReferenceEquals(_cities, value))
                {
                    var previousValue = _cities as FixupCollection<City>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCities;
                    }
                    _cities = value;
                    var newValue = value as FixupCollection<City>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCities;
                    }
                }
            }
        }
        private ICollection<City> _cities;

        #endregion

        #region Association Fixup
    
        private void FixupCities(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (City item in e.NewItems)
                {
                    item.Region = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (City item in e.OldItems)
                {
                    if (ReferenceEquals(item.Region, this))
                    {
                        item.Region = null;
                    }
                }
            }
        }

        #endregion

    }
}
