//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class SubscriptionSettings
    {
        #region Primitive Properties
    
        public virtual System.Guid Id
        {
            get;
            set;
        }
    
        public virtual bool IsSubscribed
        {
            get { return _isSubscribed; }
            set { _isSubscribed = value; }
        }
        private bool _isSubscribed = false;
    
        public virtual string EncryptedSubscriptionEmail
        {
            get;
            set;
        }
    
        public virtual byte DigestPeriodicity
        {
            get { return _digestPeriodicity; }
            set { _digestPeriodicity = value; }
        }
        private byte _digestPeriodicity = 1;

        #endregion

        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion

        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.SubscriptionSettings, this))
            {
                previousValue.SubscriptionSettings = null;
            }
    
            if (User != null)
            {
                User.SubscriptionSettings = this;
            }
        }

        #endregion

    }
}
