//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Federation.Core
{
    public partial class Voting : Content
    {
        #region Primitive Properties
    
        public virtual Nullable<short> Duration
        {
            get;
            set;
        }
    
        public virtual bool IsFinished
        {
            get { return _isFinished; }
            set { _isFinished = value; }
        }
        private bool _isFinished = false;
    
        public virtual bool HasOpenProtocol
        {
            get;
            set;
        }

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;

        #endregion

    }
}
